
    // LOAD PRODUCT LIST
export const LOAD_PRODUCTS_INITIATE = 'LOAD_PRODUCTS_INITIATE';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILED = 'LOAD_PRODUCTS_FAILED';

    // LOAD SINGLE PRODUCT
export const LOAD_SINGLE_PRODUCT_INITIATE = 'LOAD_SINGLE_PRODUCT_INITIATE';
export const LOAD_SINGLE_PRODUCT_SUCCESS = 'LOAD_SINGLE_PRODUCT_SUCCESS';
export const LOAD_SINGLE_PRODUCT_ERROR = 'LOAD_SINGLE_PRODUCT_ERROR';


export const ADD_NEW_PRODUCT_INITIATE = 'ADD_NEW_PRODUCT_INITIATE';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
export const ADD_NEW_PRODUCT_ERROR = 'ADD_NEW_PRODUCT_ERROR';

export const REQUEST_AUTHENTICATION_TOKEN_INITIATE = 'REQUEST_AUTHENTICATION_TOKEN_INITIATE';
export const REQUEST_AUTHENTICATION_TOKEN_SUCCESS = 'REQUEST_AUTHENTICATION_TOKEN_SUCCESS';
export const REQUEST_AUTHENTICATION_TOKEN_ERROR = 'REQUEST_AUTHENTICATION_TOKEN_ERROR';